name: curlfailedurls

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for branch 1 and on start directory, command.txt file changes or by manually running the workflow from actions tab
on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

env: # Or as an environment variable
  userdata: ${{ secrets.USERNAME }}
  passdata: ${{ secrets.PASSWORD }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:


      # Partial clone
      - name: Partial clone
        shell: bash
        run: |
          REPO="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git clone --filter=blob:none --no-checkout --depth 1  --sparse $REPO .
          git checkout


      - name: Running the command
        run: |
          npm install
          npm i nodemailer
          node curltest.js


      # commiting and pushing changes
      - name: commit and push
        shell: bash
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git add --sparse -A
          git commit -m "add file"
          git push
